import { generateVideoReport } from '@/lib/actions/report';
import ReactMarkdown from 'react-markdown';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

interface PageProps {
    params: Promise<{ videoId: string }>
}

export default async function ReportPage({ params }: PageProps) {
    const { videoId } = await params;

    // Generate the report on the server
    const result = await generateVideoReport(videoId);

    return (
        <div className="min-h-screen bg-[#050510] text-cyan-50 selection:bg-cyan-500/30">
            <div className="max-w-4xl mx-auto px-6 py-12">

                {/* Header Navigation */}
                <div className="mb-12">
                    <Link
                        href="/"
                        className="inline-flex items-center gap-2 text-cyan-400 hover:text-cyan-300 transition-colors py-2 pr-4"
                    >
                        <ArrowLeft size={20} />
                        <span>ホームに戻る</span>
                    </Link>
                </div>

                {/* Report Content */}
                <div className="space-y-8">
                    <div className="border-b border-cyan-900/50 pb-8">
                        <h1 className="text-3xl font-bold bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent">
                            AI詳細レポート
                        </h1>
                        <p className="mt-4 text-slate-400">
                            Video ID: <span className="font-mono text-cyan-700">{videoId}</span>
                        </p>
                    </div>

                    {result.success ? (
                        <div className="prose prose-invert prose-cyan max-w-none">
                            <div className="bg-[#0A0A1F] border border-cyan-900/30 rounded-2xl p-8 shadow-2xl shadow-cyan-900/10">
                                <ReactMarkdown
                                    components={{
                                        h2: ({ node, ...props }) => <h2 className="text-2xl font-bold text-cyan-100 mt-12 mb-6 border-l-4 border-cyan-500 pl-4" {...props} />,
                                        h3: ({ node, ...props }) => <h3 className="text-xl font-semibold text-cyan-200 mt-8 mb-4" {...props} />,
                                        ul: ({ node, ...props }) => <ul className="list-disc pl-6 space-y-2 text-slate-300 my-4" {...props} />,
                                        li: ({ node, ...props }) => <li className="pl-1" {...props} />,
                                        strong: ({ node, ...props }) => <strong className="text-cyan-400 font-semibold" {...props} />,
                                        p: ({ node, ...props }) => <p className="leading-relaxed text-slate-300 my-4" {...props} />,
                                    }}
                                >
                                    {result.markdown}
                                </ReactMarkdown>
                            </div>
                        </div>
                    ) : (
                        <div className="bg-red-950/20 border border-red-900/50 rounded-xl p-8 text-center text-red-200">
                            <h3 className="text-lg font-semibold mb-2">レポート作成エラー</h3>
                            <p>{result.error}</p>
                        </div>
                    )}
                </div>

                <div className="mt-16 pt-8 border-t border-cyan-900/30 text-center text-slate-500 text-sm">
                    Generated by Gemini 2.5 Flash
                </div>
            </div>
        </div>
    );
}
